all:	pilhaEncadeada.o
	g++	pilhaEncadeada.o	-o	pilhaEncadeada
pilhaEncadeada.o:	main-pilhaEncadeada.cpp	pilhaEncadeada.hpp
	g++	-c	main-pilhaEncadeada.cpp
clean:
	del	main-pilhaEncadeada.o
run:
	./main-pilhaEncadeada